# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Relative path to the file', max_length=2024)),
                ('size', sizefield.models.FileSizeField(default=0, help_text='Size of the file')),
                ('first_seen', models.DateTimeField(blank=True, help_text='Date the file was first scanned by the cache_manager', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountpoint', models.CharField(blank=True, help_text='Root directory of cache area', max_length=1024, unique=True)),
                ('size_bytes', sizefield.models.FileSizeField(default=0, help_text='Maximum size on the disk that can be allocated to the cache area')),
                ('allocated_bytes', sizefield.models.FileSizeField(default=0, help_text='Amount of space allocated to users')),
                ('used_bytes', sizefield.models.FileSizeField(default=0, help_text='Used value calculated by update daemon')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledDeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entered', models.DateTimeField(blank=True, help_text='Date the deletion was entered into the scheduler', null=True)),
                ('time_delete', models.DateTimeField(blank=True, help_text='Time the deletion will take place', null=True)),
                ('delete_files', models.ManyToManyField(default=None, help_text='The list of files to be deleted in this schedule', to='xfc_control.CachedFile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of user - should be same as JASMIN user name', max_length=254)),
                ('email', models.EmailField(help_text='Email of user', max_length=254)),
                ('notify', models.BooleanField(default=False, help_text='Switch notifications on / off')),
                ('quota_size', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to user, in (bytes day)')),
                ('quota_used', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to user, in (bytes day)')),
                ('hard_limit_size', sizefield.models.FileSizeField(default=0, help_text='Upper limit allocated to user, in bytes. This limit cannot be exceeded.')),
                ('total_used', sizefield.models.FileSizeField(default=0, help_text='Total size of all files owned by the user.')),
                ('cache_path', models.CharField(help_text='Relative path to cache area', max_length=2024)),
                ('cache_disk', models.ForeignKey(help_text='Cache disk allocated to the user', on_delete=django.db.models.deletion.CASCADE, to='xfc_control.CacheDisk')),
            ],
        ),
        migrations.CreateModel(
            name='UserLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lock', models.ForeignKey(blank=True, help_text='User that is locked', on_delete=django.db.models.deletion.CASCADE, to='xfc_control.User')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleddeletion',
            name='user',
            field=models.ForeignKey(help_text='User that the ScheduledDeletion belongs to', on_delete=django.db.models.deletion.CASCADE, to='xfc_control.User'),
        ),
        migrations.AddField(
            model_name='cachedfile',
            name='user',
            field=models.ForeignKey(help_text='User that owns the file', null=True, on_delete=django.db.models.deletion.CASCADE, to='xfc_control.User'),
        ),
    ]
