# Generated by Django 4.2.21 on 2026-04-21 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("xfc_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_scanned",
            field=models.DateTimeField(
                default=datetime.datetime(1900, 1, 1, 0, 0),
                help_text="The last time the user's work directory was scanned",
            ),
        ),
        migrations.CreateModel(
            name="CachedDirectoryScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dir_name", models.TextField()),
                ("scan_time", models.DateTimeField()),
                ("dir_mtime", models.DateTimeField()),
                ("size_bytes", models.BigIntegerField()),
                ("scan_id", models.CharField(db_index=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directory_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
