# Generated by Django 6.0.6 on 2026-06-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfc_control', '0003_alter_cacheddirectoryscan_id_alter_cachedfile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleddeletion',
            name='delete_files',
        ),
        migrations.RemoveField(
            model_name='scheduleddeletion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlock',
            name='user_lock',
        ),
        migrations.DeleteModel(
            name='CachedFile',
        ),
        migrations.DeleteModel(
            name='ScheduledDeletion',
        ),
        migrations.DeleteModel(
            name='UserLock',
        ),
    ]
