# Generated by Django 6.0.6 on 2026-06-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xfc_control', '0004_remove_scheduleddeletion_delete_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheddirectoryscan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_scans', to='xfc_control.user'),
        ),
    ]
